channels:
  - conda-forge

name:
  - nltools >= 0.4.2

dependencies:
  - python >= 3.6
  - pip:
    - sphinx >= 3.1.2
    - sphinx-gallery
    - sphinxcontrib-napoleon
    - sphinx_bootstrap_theme
    - networkx
    - sphinxcontrib.yt

