name: (Manual) Deploy Docs

on: workflow_dispatch

jobs:
  docs:
    name: Build docs and auto-examples
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Download and setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.8

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          conda activate test
          conda env list
          pip install -r requirements-dev.txt
          pip install -r optional-dependencies.txt

      - name: Build docs
        run: |
          cd docs
          make clean
          make html
          touch _build/html/.nojekyll
          echo 'nltools.org' > _build/html/CNAME

      - name: Deploy docs
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/_build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
